version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test-ef
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/test-ef
      DB_LOGIN: postgres
      DB_PASS: password
    ports:
      - "9999:9999"

volumes:
  postgres_data: